### ISSUE TITLE
api.get_public_rooms() limited to 50 rooms

### ISSUE THREAD

**Issue by mcenno** [dstegelman/rocket-python#16]
Title says what the issue is. Probably related to the initial number of rooms displayed on the web interface (Administration -> Rooms), which is also initially limited to 50. Would be great to get all rooms back.

**Comment by dstegelman** [comment]
We aren't doing anything to limit the amount of rooms being returned.  This must be a limitation of the rocket chat API itself.

**Comment by mcenno** [comment]
You're right, the limit is confiugurable through the web interface via Administration -> General -> REST API -> Default count. My bad!
