### ISSUE TITLE
sdist rocket-python-1.2.3.tar.gz  from pypi incomplete

### ISSUE THREAD

**Issue by toabctl** [dstegelman/rocket-python#19]
The sdist tarball on pypi does not contain all needed files. Eg the README.md is missing which leads to:
```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description=open("README.md", "r").read(),
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

Not sure how you created the sdist, but you can just do:
```
python setup.py sdist
```

And then upload the tarball from the ```dist``` dir. I tried that locally and the sdist tarball I created was complete.

**Comment by dstegelman** [comment]
Should be fixed in 1.2.4
